### ISSUE TITLE
Validar Login

### ISSUE THREAD

**Issue by ninagallo** [ninagallo/cdmx-2018-06-bc-core-am-social-network#4]
Hacer la funcion de validacion de Login, en este caso se utilizara firebase.

**Comment by florenciasilva** [comment]
Mediante nuestra funcion de registro, se guardan los datos. A continuación, para hacer sign in, se comprueba que el email y contraseña ya hayan sido registrados, que tengan un formato valido y que la contraseña no sea menor a 6 caracteres.
En caso de error, se mostrará una alerta con el mensaje de error. En caso de un log in exitoso, se continuará a la página inicial de la red social.

**Comment by ninagallo** [comment]
Ya se hicieron las pruebas del funcionamiento del log in. En caso de futuros problemas los comentaremos en la proxima milestone titulada Sprint 2.
