### ISSUE TITLE
Caja de comentarios

### ISSUE THREAD

**Issue by ninagallo** [ninagallo/cdmx-2018-06-bc-core-am-social-network#6]
Crear caja de comentarios y que se pueda imprimir el primer comentarios en la pagina

**Comment by florenciasilva** [comment]
Creación de area de texto terminada, con botón para enviar los datos y que los mismos se impriman debajo. Se utiliza un formato card para visualizar los elementos.

**Comment by ninagallo** [comment]
Listo, por este sprint quedo terminada la caja, el proximo issue los veremos en la proxima milestone titulada Sprint 2.
